config/routes.rb
Rails.application.routes.draw do
  if ENV['WITH_SWAGGER_DOCS'].presence
    mount Rswag::Ui::Engine => '/api-docs'
    mount Rswag::Api::Engine => '/api-docs'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root to: 'home#index'

  mount_devise_token_auth_for 'User', at: 'api/v1/auth', skip: %i[
    registrations
    token_validations
    omniauth_callbacks
    unlocks
  ], controllers: {
    sessions: 'api/v1/auth/sessions',
  }

  namespace :api do
    namespace :v1 do
      resources :absence_reasons
      resources :absence_requests do
        member do
          put :cancel
        end
      end
      resources :clients
      resources :construction_sites
      resources :estimations do
        resources :estimation_rooms, controller: 'estimations/estimation_rooms' do
          resources :estimation_items, controller: 'estimations/estimation_rooms/estimation_items'
        end
      end
      resources :materials
      resources :users
      resources :work_entries
      resources :notifications, only: %i[index] do
        member do
          put :read
        end
      end
    end
  end

  namespace :workspace do
    get 'dashboard', to: 'dashboard#index'
    devise_for :users, only: %i[sessions confirmations passwords], controllers: {
      sessions: 'devise/sessions',
      confirmations: 'devise/confirmations',
      passwords: 'devise/passwords',
    }
    resources :absence_reasons
    resources :absence_requests do
      member do
        put :accept
        put :reject
        put :cancel
      end
    end
    resources :clients
    resources :construction_sites
    resources :estimations do
      member do
        get :print
      end
    end
    resources :materials
    resources :users
    resources :work_entries
  end

  resources :examples, only: [] do
    collection do
      get :estimation
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/workspace/absence_reasons_controller.rb
class Workspace::AbsenceReasonsController < Workspace::BaseController
  include WorkspaceCrud

  workspace_crud(AbsenceReason)

  set_form_attributes %i[name]
  set_table_attributes %i[name]
end

app/controllers/workspace/absence_requests_controller.rb
class Workspace::AbsenceRequestsController < Workspace::BaseController
  include WorkspaceCrud

  workspace_crud(AbsenceRequest)

  query_transform { |q| q.includes(:absence_reason, :employee) }

  set_form_attributes(
    [
      proc do |ctx, f|
        f.association(
          :employee,
          collection: UserPolicy.new(user: ctx.current_workspace_user).authorized_scope(User.all).decorate,
          include_blank: false
        )
      end,
      proc do |ctx, f|
        f.association(
          :absence_reason,
          collection: AbsenceReasonPolicy.new(user: ctx.current_workspace_user).authorized_scope(AbsenceReason.all).decorate,
          include_blank: false
        )
      end,
      proc { |ctx, f| f.input :status, collection: ctx.enum_for_select(AbsenceRequest, :status), include_blank: false },
      :from,
      :to,
      :note
    ]
  )
  set_table_attributes(
    [
      :employee,
      :from,
      :to,
      [:status, proc { |ctx, res| ctx.te(AbsenceRequest, :status, res.status) }],
      :absence_reason,
      :note
    ]
  )

  set_additional_table_actions(
    [
      proc do |ctx, res|
        ctx.link_to(
          '✔️',
          ctx.accept_workspace_absence_request_path(res),
          method: :put
        ) if res.accept? && ctx.allowed_to?(:accept?, res.object)
      end,
      proc do |ctx, res|
        ctx.link_to(
          '❌',
          ctx.reject_workspace_absence_request_path(res),
          method: :put
        ) if res.reject? && ctx.allowed_to?(:reject?, res.object)
      end,
      proc do |ctx, res|
        ctx.link_to(
          '✖️',
          ctx.cancel_workspace_absence_request_path(res),
          method: :put
        ) if res.cancel? && ctx.allowed_to?(:cancel?, res.object)
      end
    ]
  )

  create_with(AbsenceRequests::CreateAbsenceRequest)

  def accept
    custom_action_with(AbsenceRequests::AcceptAbsenceRequest)
  end

  def reject
    custom_action_with(AbsenceRequests::RejectAbsenceRequest)
  end

  def cancel
    custom_action_with(AbsenceRequests::CancelAbsenceRequest)
  end
end

app/controllers/workspace/base_controller.rb
class Workspace::BaseController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_workspace_user!
  before_action :load_company

  layout 'workspace'

  responders :flash, :http_cache, :collection
  respond_to :html

  private

  def load_company
    @company = authorized_scope(Company.all).find(current_workspace_user.company_id)
  end

  def current_user
    current_workspace_user
  end
end

app/controllers/workspace/clients_controller.rb
class Workspace::ClientsController < Workspace::BaseController
  include WorkspaceCrud

  workspace_crud(Client)

  set_form_attributes %i[first_name last_name email phone]
  set_table_attributes %i[first_name last_name email phone]
end

app/controllers/workspace/construction_sites_controller.rb
class Workspace::ConstructionSitesController < Workspace::BaseController
  include WorkspaceCrud

  workspace_crud(ConstructionSite)

  set_form_attributes %i[name investment_time_from investment_time_to active]
  set_table_attributes(
    [
      :name,
      :investment_time_from,
      :investment_time_to,
      [:active, proc { |ctx, res| ctx.tb(res.active) }]
    ]
  )
end

app/controllers/workspace/dashboard_controller.rb
class Workspace::DashboardController < Workspace::BaseController
  decorates_assigned :work_entries
  decorates_assigned :absence_requests

  def index
    @work_entries = authorized_scope(WorkEntry.all)
                    .includes(:absence_reason, :construction_site, :employee).order(created_at: :desc).limit(5)
    @absence_requests = authorized_scope(AbsenceRequest.all)
                        .includes(:absence_reason, :employee).order(created_at: :desc).limit(5)
  end
end

app/controllers/workspace/estimations_controller.rb
class Workspace::EstimationsController < Workspace::BaseController
  include WorkspaceCrud

  workspace_crud(Estimation)

  query_transform { |q| q.includes(:client) }

  set_table_attributes %i[name client created_at]

  set_additional_table_actions([proc { |ctx, res| ctx.link_to '🖨️', ctx.print_workspace_estimation_path(res), target: '_blank' }])

  params_transform do |ctx, prms|
    prms[:creator_id] = ctx.current_workspace_user.id

    prms
  end

  def print
    load_resource
    html = render_to_string 'companies/estimations/report', layout: 'pdf'
    send_data PdfGenerationService.new.call(html, wkhtmltopdf_options: estimation.pdf_options),
              filename: t('workspace.estimations.filename'),
              type: 'application/pdf',
              disposition: 'inline'
  end
end

app/controllers/workspace/materials_controller.rb
class Workspace::MaterialsController < Workspace::BaseController
  include WorkspaceCrud

  workspace_crud(Material)

  set_form_attributes(
    [
      :name,
      proc { |ctx, f| f.input :unit, collection: ctx.enum_for_select(Material, :unit) },
      :price
    ]
  )
  set_table_attributes(
    [
      :name,
      [:unit, proc { |ctx, res| ctx.te(Material, :unit, res.unit) }],
      :price
    ]
  )
end

app/controllers/workspace/users_controller.rb
class Workspace::UsersController < Workspace::BaseController
  include WorkspaceCrud

  workspace_crud(User)

  query_transform { |q| q.includes(:roles) }

  set_form_attributes %i[first_name last_name username email password password_confirmation]

  set_table_attributes(
    [
      :first_name,
      :last_name,
      :role
    ]
  )

  params_transform do |_, prms|
    if prms[:password].blank?
      prms[:password] = nil
      prms[:password_confirmation] = nil
    end

    prms
  end

  create_with(Users::CreateEmployee)
end

app/controllers/workspace/work_entries_controller.rb
class Workspace::WorkEntriesController < Workspace::BaseController
  include WorkspaceCrud

  workspace_crud(WorkEntry)

  query_transform { |q| q.includes(:absence_reason, :employee, :construction_site) }

  set_form_attributes(
    [
      :day,
      proc do |ctx, f|
        f.association(
          :employee,
          collection: UserPolicy.new(user: ctx.current_workspace_user).authorized_scope(User.all).decorate,
          include_blank: false
        )
      end,
      proc do |ctx, f|
        f.association(
          :construction_site,
          collection: ConstructionSitePolicy.new(user: ctx.current_workspace_user).authorized_scope(ConstructionSite.all).decorate,
          include_blank: false
        )
      end,
      proc do |ctx, f|
        f.association(
          :absence_reason,
          collection: AbsenceReasonPolicy.new(user: ctx.current_workspace_user).authorized_scope(AbsenceReason.all).decorate,
          include_blank: false
        )
      end,
      :spent_time,
      :notes
    ]
  )
  set_table_attributes(
    %i[
      day
      employee
      construction_site
      absence_reason
      spent_time
      notes
    ]
  )

  create_with(WorkEntries::CreateWorkEntry)
end

app/views/workspace/dashboard/_absence_requests.slim
.mt-10.mb-5.text-4xl.font-bold= [t('latest'), t('workspace.absence_requests.index.title').downcase].join(' ')
table.table
  thead
    tr
      - %i[employee from to status absence_reason note].each do |key|
        th= ta(AbsenceRequest, key)
      th colspan=4 
  tbody
    - absence_requests.each do |resource|
      tr
        - [:employee,
          :from,
          :to,
          [:status, proc { |ctx, res| ctx.te(AbsenceRequest, :status, res.status) }],
          :absence_reason,
          :note].each do |attribute|
          - if attribute.is_a?(Symbol)
            td= resource.send(attribute)
          - else
            td= attribute.second.(self, resource)
        - if !resource.rejected? && allowed_to?(:reject?, resource.object)
          td.w-8= link_to '❌', workspace_absence_request_path(resource,
                    absence_request: { status: :rejected }, referer: workspace_dashboard_path), method: :put
        - else
          td.w-8
        - if !resource.accepted? && allowed_to?(:accept?, resource.object)
          td.w-8= link_to '✔️', workspace_absence_request_path(resource,
                    absence_request: { status: :accepted }, referer: workspace_dashboard_path), method: :put
        - else
          td.w-8
        td.w-8= link_to '✏️', edit_workspace_absence_request_path(resource)
        td.w-8= link_to '🗑️', workspace_absence_request_path(resource, referer: workspace_dashboard_path),
                        method: :delete, data: { confirm: t('sure') } if allowed_to?(:destroy?, resource.object)

app/views/workspace/dashboard/_employee_dashboard.slim
.flex.justify-around
  = link_to t('.new_work_entry'), new_workspace_work_entry_path, class: 'btn'
  = link_to t('.new_absence_request'), new_workspace_absence_request_path, class: 'btn'
= render 'work_entries'
= render 'absence_requests'

app/views/workspace/dashboard/_owner_dashboard.slim
= render 'work_entries'
= render 'absence_requests'

app/views/workspace/dashboard/_work_entries.slim
.mt-10.mb-5.text-4xl.font-bold= [t('latest'), t('workspace.work_entries.index.title').downcase].join(' ')
table.table
  thead
    tr
      - %i[day employee construction_site absence_reason spent_time notes].each do |key|
        th= ta(WorkEntry, key)
      th colspan=2 

  tbody
    - work_entries.each do |work_entry|
      tr
        - %i[day employee construction_site absence_reason spent_time notes].each do |key|
          td= work_entry.send(key)
        td.w-8= link_to '✏️', edit_workspace_work_entry_path(work_entry)
        td.w-8= link_to '🗑️', workspace_work_entry_path(work_entry, referer: workspace_dashboard_path),
                        method: :delete, data: { confirm: t('sure') } if allowed_to?(:destroy?, work_entry.object)

app/views/workspace/dashboard/index.slim
= render 'owner_dashboard' if current_workspace_user.owner?
= render 'employee_dashboard' if current_workspace_user.employee?